title: Project

fields:
  caption:
    label: En bref
    type: writer
    inline: true
    marks:
      - italic

  image_cover:
    label: Image de couverture
    type: files
    uploads:
      accept: image/*
    max: 1
    min: 1
    required: true
    layout: cards
    image:
      back: black
    size: huge
    width: 1/2

  tags:
    label: Type de projet
    type: pages
    query: site.find('tags').children
    multiple: true
    layout: list
    width: 1/2


  intention:
    label: Intention
    type: list

  description:
    label: Description
    type: writer
    nodes:
      - paragraph
    marks:
      - italic
      - link

  content:
    label: Contenu
    type: blocks
    fieldsets:
      texte:
        wysiwyg: true
        preview: fields
        fields:
          text:
            type: writer
            nodes:
              - paragraph
              - bulletList
              - orderedList
            marks:
              - bold
              - italic
              - link
      gallery:
        label: Galerie
        preview: fields
        wysiwyg: true
        fields:
          images:
            label: 'images'
            type: files
            query: model.images
            multiple: true
            min: 2
            layout: cards
            size: small
            uploads:
              template: blocks/image
          caption:
            label: field.blocks.image.caption
            type: writer
            icon: text
            inline: true

      podcast:
        label: Podcast Spotify
        icon: audio
        preview: fields
        wysiwyg: true
        fields:
          spotify_url:
            label: URL Spotify
            type: url
            placeholder: https://open.spotify.com/episode/...
      video:
        label: Vidéo
        preview: fields
        wysiwyg: true
        fields:
          url:
            label: field.blocks.video.url.label
            type: url
            placeholder: field.blocks.video.url.placeholder
          caption:
            label: Légende
            type: writer
            inline: true
            marks:
              - bold
              - italic
              - link
          credits:
            width: 2/3
            label: crédits
            type: writer
            inline: true
            marks:
              - bold
              - italic
              - link
          date:
            width: 1/3
            label: Date
            type: date
      cards:
        label: Cards
        wysiwyg: true
        preview: fields
        name: Cards
        icon: grid
        fields:
          cards_titre:
            label: Titre
            type: text
          cards:
            label: Cards
            type: structure
            fields:
              text:
                label: Text
                type: writer
                inline: true
                marks:
                  - italic
              baseline:
                label: baseline
                type: text
