title: Project

fields:
  caption:
    label: En bref
    type: writer
    inline: true
    marks:
      - italic

  image_cover:
    label: Image de couverture
    type: files
    uploads:
      accept: image/*
    max: 1
    min: 1
    required: true
    layout: cards
    image:
      back: black
    size: huge
    width: 1/2

  tags:
    label: Type de projet
    type: pages
    query: site.find('tags').children
    multiple: true
    layout: list
    width: 1/2


  intention:
    label: Intention
    type: list

  description:
    label: Description
    type: writer
    nodes:
      - paragraph
    marks:
      - italic
      - link

  content:
    label: Contenu
    type: blocks
    fieldsets:
      - texte
      - gallery
      - podcast
      - video
      - cards
      - article_heading
