title: Site


columns:
  - width: 1/3
    sections:
      tags:
        label: Les tags
        type: pages
        template:
          - tags
        status: listed
        image:
          back: white
          query: false
      projects:
        label: Les projets
        layout: cards
        type: pages
        status: listed
        templates:
          - projects
        image:
          back: white
          query: false

  - width: 2/3
    sections:
      pages:
        label: Autre pages
        layout: cards
        type: pages
        templates:
          - default
        image:
          back: white
          query: false

