title: Site
options:
  preview: "https://facenord.max-esnee.com"

columns:
  - width: 1/4
    sections:
      home:
        label: La page d'accueil
        type: pages
        template:
          - home
        status: listed
        layout: cards
        size: small
        image:
          back: white
          query: false
  - width: 1/4
    sections:
      projects:
        label: Les projets
        layout: cards
        type: pages
        status: listed
        size: small
        templates:
          - projects
        image:
          back: white
          query: false
      tags:
        label: Les tags
        type: pages
        template:
          - tags
        status: listed
        image:
          back: white
          query: false

  - width: 2/4
    sections:
      pages:
        label: Autre pages
        layout: cards
        size: small
        type: pages
        templates:
          - default
        image:
          back: white
          query: false
  - width: 4/4
    sections:
      fields:
        label: Pied de page
        type: fields
        fields:
          headline:
            type: headline
            label: Pied de page
          footer_address:
            label: Adresse
            type: writer
            inline: true
            marks:
              - bold
              - italic
          footer_links:
            label: Liens
            type: pages
            query: site.index.filterBy('template', 'not in', ['tags', 'tag'])

        
